### ISSUE TITLE
 Max retries exceeded with url: /LATEST_RELEASE_97.0.4692 (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

### ISSUE THREAD

**Issue by doulemint** [wassimbj/educative.io-pdf-downloader#1]
Hello, do you know how to fix this error?

====== WebDriver manager ======
Current google-chrome version is 97.0.4692
Get LATEST chromedriver version for 97.0.4692 google-chrome
Traceback (most recent call last):
  File "C:\Users\stone\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\stone\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\stone\AppData\Roaming\Python\Python38\site-packages\urllib3\connection.py", line 364, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\stone\AppData\Roaming\Python\Python38\site-packages\urllib3\connection.py", line 501, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "C:\Users\stone\AppData\Roaming\Python\Python38\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\stone\AppData\Roaming\Python\Python38\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "E:\Aanaconda\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\Aanaconda\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "E:\Aanaconda\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\stone\AppData\Roaming\Python\Python38\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\stone\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\stone\AppData\Roaming\Python\Python38\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='chromedriver.storage.googleapis.com', port=443): Max retries exceeded with url: /LATEST_RELEASE_97.0.4692 (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 25, in <module>
    s = Service(ChromeDriverManager().install())
  File "E:\Aanaconda\lib\site-packages\webdriver_manager\chrome.py", line 32, in install
    driver_path = self._get_driver_path(self.driver)
  File "E:\Aanaconda\lib\site-packages\webdriver_manager\manager.py", line 23, in _get_driver_path
    driver_version = driver.get_version()
  File "E:\Aanaconda\lib\site-packages\webdriver_manager\driver.py", line 41, in get_version
    return self.get_latest_release_version()
  File "E:\Aanaconda\lib\site-packages\webdriver_manager\driver.py", line 70, in get_latest_release_version
    resp = requests.get(
  File "C:\Users\stone\AppData\Roaming\Python\Python38\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\stone\AppData\Roaming\Python\Python38\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\stone\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\stone\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\stone\AppData\Roaming\Python\Python38\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='chromedriver.storage.googleapis.com', port=443): Max retries exceeded with url: /LATEST_RELEASE_97.0.4692 (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

**Comment by wassimbj** [comment]
did you follow the usage section in the readme file ? cause I can't help so much here unless I see your environment

**Comment by doulemint** [comment]
yes! I download all library and was able to run. I guess this issue has to do with my account?

**Comment by wassimbj** [comment]
i don't know, do you have an account ? looks like it tried to make an http request but it failed somehow,, try checking any firewall settings
